language: python
python:
- '2.7'
env:
  global:
  - ARTIFACTS_AWS_REGION=us-east-1
  - ARTIFACTS_S3_BUCKET=travis-sentry-comments
  - secure: NStoOoQHEtYB1ClkpjgVHYQHYEXvEZqqfKMRpPd+Z0Z6rNeZXhilKzCvqvsm5lqd53kPPGYnEfVZgL51ulGygICgtEuMfofxIZwgLGcMet0LWpD1pyqqmFQ9PrPurG/g6pxGNtNxG13bxTwXlqNIcvht2i7w1ie28+wJRMG7x8c=
  - secure: AjimGNmh69U0gX5Qug1c7LlxIXx4e6g1CC82wvmUBhCkJBRBnHXmIZU1PwMcLf/qZy718NQI8BuF+uhOKJOoI6pevHZoCvIjoH5Yxan/Y+sE3cUFG96THFhpwDERJxkSNvB1lOD0l3yOrUgaUj/MaAQLMtOG3PbYOVectxxzXg8=
before_script:
- gem install travis-artifacts
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- wget http://selenium.googlecode.com/files/selenium-server-standalone-2.38.0.jar
- java -jar selenium-server-standalone-2.38.0.jar &> selenium.log &
after_failure:
- travis-artifacts upload --path selenium.log --path test_results/
install: pip install tox
script: tox
